=begin
#Spartera API Documentation

#Auto-generated API documentation for REST services of the Spartera platform

The version of the OpenAPI document: 1.25.0
Contact: support@spartera.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module OpenapiClient
  # Input schema for creating ApiKey
  class ApiKeysInput < ApiModelBase
    # User who owns this API key
    attr_accessor :user_id

    # Company this API key belongs to
    attr_accessor :company_id

    # Role/permission level for this API key
    attr_accessor :role_id

    # Type of API key (analytics, mcp, or endpoint)
    attr_accessor :key_type

    # True if key was auto-generated for MCP deployment
    attr_accessor :is_system_generated

    # MCP deployment this key is tied to (NULL for analytics/endpoint keys)
    attr_accessor :mcp_deployment_id

    # Endpoint this key is tied to (NULL for analytics/mcp keys)
    attr_accessor :endpoint_id

    # Human-readable name for this API key
    attr_accessor :name

    # When this API key expires (NULL = never expires)
    attr_accessor :expiration_date_utc

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'user_id' => :'user_id',
        :'company_id' => :'company_id',
        :'role_id' => :'role_id',
        :'key_type' => :'key_type',
        :'is_system_generated' => :'is_system_generated',
        :'mcp_deployment_id' => :'mcp_deployment_id',
        :'endpoint_id' => :'endpoint_id',
        :'name' => :'name',
        :'expiration_date_utc' => :'expiration_date_utc'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'user_id' => :'String',
        :'company_id' => :'String',
        :'role_id' => :'Integer',
        :'key_type' => :'String',
        :'is_system_generated' => :'Boolean',
        :'mcp_deployment_id' => :'String',
        :'endpoint_id' => :'String',
        :'name' => :'String',
        :'expiration_date_utc' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::ApiKeysInput` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::ApiKeysInput`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      end

      if attributes.key?(:'company_id')
        self.company_id = attributes[:'company_id']
      else
        self.company_id = nil
      end

      if attributes.key?(:'role_id')
        self.role_id = attributes[:'role_id']
      else
        self.role_id = nil
      end

      if attributes.key?(:'key_type')
        self.key_type = attributes[:'key_type']
      end

      if attributes.key?(:'is_system_generated')
        self.is_system_generated = attributes[:'is_system_generated']
      end

      if attributes.key?(:'mcp_deployment_id')
        self.mcp_deployment_id = attributes[:'mcp_deployment_id']
      end

      if attributes.key?(:'endpoint_id')
        self.endpoint_id = attributes[:'endpoint_id']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'expiration_date_utc')
        self.expiration_date_utc = attributes[:'expiration_date_utc']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @company_id.nil?
        invalid_properties.push('invalid value for "company_id", company_id cannot be nil.')
      end

      if @role_id.nil?
        invalid_properties.push('invalid value for "role_id", role_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @company_id.nil?
      return false if @role_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] company_id Value to be assigned
    def company_id=(company_id)
      if company_id.nil?
        fail ArgumentError, 'company_id cannot be nil'
      end

      @company_id = company_id
    end

    # Custom attribute writer method with validation
    # @param [Object] role_id Value to be assigned
    def role_id=(role_id)
      if role_id.nil?
        fail ArgumentError, 'role_id cannot be nil'
      end

      @role_id = role_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          user_id == o.user_id &&
          company_id == o.company_id &&
          role_id == o.role_id &&
          key_type == o.key_type &&
          is_system_generated == o.is_system_generated &&
          mcp_deployment_id == o.mcp_deployment_id &&
          endpoint_id == o.endpoint_id &&
          name == o.name &&
          expiration_date_utc == o.expiration_date_utc
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [user_id, company_id, role_id, key_type, is_system_generated, mcp_deployment_id, endpoint_id, name, expiration_date_utc].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
