=begin
#Spartera API Documentation

#Auto-generated API documentation for REST services of the Spartera platform

The version of the OpenAPI document: 1.25.0
Contact: support@spartera.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module OpenapiClient
  # A saved marketplace asset in a user's favorites library
  class Favorites < ApiModelBase
    # Optional.
    attr_accessor :date_created

    # Optional.
    attr_accessor :last_updated

    # Auto-generated unique identifier.
    attr_accessor :favorite_id

    # References assets.asset_id — A published analytics asset — a calculation or visualization built on a data connection. See GET /assets for valid values. Required.
    attr_accessor :asset_id

    # References users.user_id — An individual user account within a company. See GET /users for valid values. Optional.
    attr_accessor :user_id

    # References companies.company_id — A Spartera seller or buyer company account. See GET /companies for valid values. Required.
    attr_accessor :company_id

    # Optional user notes about this favorite
    attr_accessor :notes

    # Optional category for organizing favorites (e.g., 'Work', 'Research')
    attr_accessor :category

    # User-defined priority for sorting (higher = more important)
    attr_accessor :priority

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'date_created' => :'date_created',
        :'last_updated' => :'last_updated',
        :'favorite_id' => :'favorite_id',
        :'asset_id' => :'asset_id',
        :'user_id' => :'user_id',
        :'company_id' => :'company_id',
        :'notes' => :'notes',
        :'category' => :'category',
        :'priority' => :'priority'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'date_created' => :'Time',
        :'last_updated' => :'Time',
        :'favorite_id' => :'Integer',
        :'asset_id' => :'String',
        :'user_id' => :'String',
        :'company_id' => :'String',
        :'notes' => :'String',
        :'category' => :'String',
        :'priority' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::Favorites` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::Favorites`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'date_created')
        self.date_created = attributes[:'date_created']
      end

      if attributes.key?(:'last_updated')
        self.last_updated = attributes[:'last_updated']
      end

      if attributes.key?(:'favorite_id')
        self.favorite_id = attributes[:'favorite_id']
      end

      if attributes.key?(:'asset_id')
        self.asset_id = attributes[:'asset_id']
      else
        self.asset_id = nil
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      end

      if attributes.key?(:'company_id')
        self.company_id = attributes[:'company_id']
      else
        self.company_id = nil
      end

      if attributes.key?(:'notes')
        self.notes = attributes[:'notes']
      end

      if attributes.key?(:'category')
        self.category = attributes[:'category']
      end

      if attributes.key?(:'priority')
        self.priority = attributes[:'priority']
      else
        self.priority = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @asset_id.nil?
        invalid_properties.push('invalid value for "asset_id", asset_id cannot be nil.')
      end

      if @company_id.nil?
        invalid_properties.push('invalid value for "company_id", company_id cannot be nil.')
      end

      if @priority.nil?
        invalid_properties.push('invalid value for "priority", priority cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @asset_id.nil?
      return false if @company_id.nil?
      return false if @priority.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] asset_id Value to be assigned
    def asset_id=(asset_id)
      if asset_id.nil?
        fail ArgumentError, 'asset_id cannot be nil'
      end

      @asset_id = asset_id
    end

    # Custom attribute writer method with validation
    # @param [Object] company_id Value to be assigned
    def company_id=(company_id)
      if company_id.nil?
        fail ArgumentError, 'company_id cannot be nil'
      end

      @company_id = company_id
    end

    # Custom attribute writer method with validation
    # @param [Object] priority Value to be assigned
    def priority=(priority)
      if priority.nil?
        fail ArgumentError, 'priority cannot be nil'
      end

      @priority = priority
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          date_created == o.date_created &&
          last_updated == o.last_updated &&
          favorite_id == o.favorite_id &&
          asset_id == o.asset_id &&
          user_id == o.user_id &&
          company_id == o.company_id &&
          notes == o.notes &&
          category == o.category &&
          priority == o.priority
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [date_created, last_updated, favorite_id, asset_id, user_id, company_id, notes, category, priority].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
