=begin
#Spartera API Documentation

#Auto-generated API documentation for REST services of the Spartera platform

The version of the OpenAPI document: 1.25.0
Contact: support@spartera.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module OpenapiClient
  # Available industry categories for asset classification. Based on US NAISC codes.
  class Industries < ApiModelBase
    # Optional.
    attr_accessor :date_created

    # Optional.
    attr_accessor :last_updated

    # Auto-generated unique identifier.
    attr_accessor :industry_id

    # Required. Must be unique.
    attr_accessor :industry_name

    # Required.
    attr_accessor :short_name

    # Optional.
    attr_accessor :slug

    # Optional.
    attr_accessor :naisc_code

    # Optional.
    attr_accessor :description

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'date_created' => :'date_created',
        :'last_updated' => :'last_updated',
        :'industry_id' => :'industry_id',
        :'industry_name' => :'industry_name',
        :'short_name' => :'short_name',
        :'slug' => :'slug',
        :'naisc_code' => :'naisc_code',
        :'description' => :'description'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'date_created' => :'Time',
        :'last_updated' => :'Time',
        :'industry_id' => :'Integer',
        :'industry_name' => :'String',
        :'short_name' => :'String',
        :'slug' => :'String',
        :'naisc_code' => :'Integer',
        :'description' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::Industries` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::Industries`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'date_created')
        self.date_created = attributes[:'date_created']
      end

      if attributes.key?(:'last_updated')
        self.last_updated = attributes[:'last_updated']
      end

      if attributes.key?(:'industry_id')
        self.industry_id = attributes[:'industry_id']
      end

      if attributes.key?(:'industry_name')
        self.industry_name = attributes[:'industry_name']
      else
        self.industry_name = nil
      end

      if attributes.key?(:'short_name')
        self.short_name = attributes[:'short_name']
      else
        self.short_name = nil
      end

      if attributes.key?(:'slug')
        self.slug = attributes[:'slug']
      end

      if attributes.key?(:'naisc_code')
        self.naisc_code = attributes[:'naisc_code']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @industry_name.nil?
        invalid_properties.push('invalid value for "industry_name", industry_name cannot be nil.')
      end

      if @short_name.nil?
        invalid_properties.push('invalid value for "short_name", short_name cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @industry_name.nil?
      return false if @short_name.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] industry_name Value to be assigned
    def industry_name=(industry_name)
      if industry_name.nil?
        fail ArgumentError, 'industry_name cannot be nil'
      end

      @industry_name = industry_name
    end

    # Custom attribute writer method with validation
    # @param [Object] short_name Value to be assigned
    def short_name=(short_name)
      if short_name.nil?
        fail ArgumentError, 'short_name cannot be nil'
      end

      @short_name = short_name
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          date_created == o.date_created &&
          last_updated == o.last_updated &&
          industry_id == o.industry_id &&
          industry_name == o.industry_name &&
          short_name == o.short_name &&
          slug == o.slug &&
          naisc_code == o.naisc_code &&
          description == o.description
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [date_created, last_updated, industry_id, industry_name, short_name, slug, naisc_code, description].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
