=begin
#Spartera API Documentation

#Auto-generated API documentation for REST services of the Spartera platform

The version of the OpenAPI document: 1.25.0
Contact: support@spartera.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module OpenapiClient
  # An AI-generated article or post created by the Spartera Post Generator
  class Posts < ApiModelBase
    # Optional.
    attr_accessor :date_created

    # Optional.
    attr_accessor :last_updated

    # Unique identifier.
    attr_accessor :post_id

    # User who created this post
    attr_accessor :user_id

    # Company this post belongs to
    attr_accessor :company_id

    # Article title
    attr_accessor :title

    # Article category (e.g., 'Sports', 'Business')
    attr_accessor :category

    # Article teaser/subtitle
    attr_accessor :teaser

    # Generated article HTML content
    attr_accessor :content_html

    # Array of insights used: [{asset_id, asset_name, value, runtime, success}]
    attr_accessor :insights_used

    # Creativity level (0-100), maps to AI temperature
    attr_accessor :generation_creativity

    # Target word count (null = auto)
    attr_accessor :generation_target_word_count

    # Writing tone: professional, casual, technical, conversational
    attr_accessor :generation_tone

    # Whether to include data source citations
    attr_accessor :generation_include_citations

    # Number of subheadings (2-5)
    attr_accessor :generation_subheading_count

    # Actual temperature used for generation (0.0-2.0)
    attr_accessor :generation_temperature

    # Cost in credits for data insights
    attr_accessor :data_cost_credits

    # Cost in credits for AI generation service
    attr_accessor :service_cost_credits

    # Total cost in credits (data + service)
    attr_accessor :total_cost_credits

    # Number of insights that succeeded
    attr_accessor :successful_insights_count

    # Number of insights that failed
    attr_accessor :failed_insights_count

    # Time taken to generate article in milliseconds
    attr_accessor :generation_time_ms

    # Whether this post has been published
    attr_accessor :is_published

    # When this post was published
    attr_accessor :published_at

    # Number of times this post has been viewed
    attr_accessor :view_count

    # When this post was last edited
    attr_accessor :last_edited_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'date_created' => :'date_created',
        :'last_updated' => :'last_updated',
        :'post_id' => :'post_id',
        :'user_id' => :'user_id',
        :'company_id' => :'company_id',
        :'title' => :'title',
        :'category' => :'category',
        :'teaser' => :'teaser',
        :'content_html' => :'content_html',
        :'insights_used' => :'insights_used',
        :'generation_creativity' => :'generation_creativity',
        :'generation_target_word_count' => :'generation_target_word_count',
        :'generation_tone' => :'generation_tone',
        :'generation_include_citations' => :'generation_include_citations',
        :'generation_subheading_count' => :'generation_subheading_count',
        :'generation_temperature' => :'generation_temperature',
        :'data_cost_credits' => :'data_cost_credits',
        :'service_cost_credits' => :'service_cost_credits',
        :'total_cost_credits' => :'total_cost_credits',
        :'successful_insights_count' => :'successful_insights_count',
        :'failed_insights_count' => :'failed_insights_count',
        :'generation_time_ms' => :'generation_time_ms',
        :'is_published' => :'is_published',
        :'published_at' => :'published_at',
        :'view_count' => :'view_count',
        :'last_edited_at' => :'last_edited_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'date_created' => :'Time',
        :'last_updated' => :'Time',
        :'post_id' => :'String',
        :'user_id' => :'String',
        :'company_id' => :'String',
        :'title' => :'String',
        :'category' => :'String',
        :'teaser' => :'String',
        :'content_html' => :'String',
        :'insights_used' => :'Object',
        :'generation_creativity' => :'Integer',
        :'generation_target_word_count' => :'Integer',
        :'generation_tone' => :'String',
        :'generation_include_citations' => :'Boolean',
        :'generation_subheading_count' => :'Integer',
        :'generation_temperature' => :'Float',
        :'data_cost_credits' => :'Integer',
        :'service_cost_credits' => :'Integer',
        :'total_cost_credits' => :'Integer',
        :'successful_insights_count' => :'Integer',
        :'failed_insights_count' => :'Integer',
        :'generation_time_ms' => :'Integer',
        :'is_published' => :'Boolean',
        :'published_at' => :'Time',
        :'view_count' => :'Integer',
        :'last_edited_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::Posts` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::Posts`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'date_created')
        self.date_created = attributes[:'date_created']
      end

      if attributes.key?(:'last_updated')
        self.last_updated = attributes[:'last_updated']
      end

      if attributes.key?(:'post_id')
        self.post_id = attributes[:'post_id']
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      else
        self.user_id = nil
      end

      if attributes.key?(:'company_id')
        self.company_id = attributes[:'company_id']
      else
        self.company_id = nil
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      else
        self.title = nil
      end

      if attributes.key?(:'category')
        self.category = attributes[:'category']
      end

      if attributes.key?(:'teaser')
        self.teaser = attributes[:'teaser']
      end

      if attributes.key?(:'content_html')
        self.content_html = attributes[:'content_html']
      else
        self.content_html = nil
      end

      if attributes.key?(:'insights_used')
        self.insights_used = attributes[:'insights_used']
      end

      if attributes.key?(:'generation_creativity')
        self.generation_creativity = attributes[:'generation_creativity']
      end

      if attributes.key?(:'generation_target_word_count')
        self.generation_target_word_count = attributes[:'generation_target_word_count']
      end

      if attributes.key?(:'generation_tone')
        self.generation_tone = attributes[:'generation_tone']
      end

      if attributes.key?(:'generation_include_citations')
        self.generation_include_citations = attributes[:'generation_include_citations']
      end

      if attributes.key?(:'generation_subheading_count')
        self.generation_subheading_count = attributes[:'generation_subheading_count']
      end

      if attributes.key?(:'generation_temperature')
        self.generation_temperature = attributes[:'generation_temperature']
      end

      if attributes.key?(:'data_cost_credits')
        self.data_cost_credits = attributes[:'data_cost_credits']
      else
        self.data_cost_credits = nil
      end

      if attributes.key?(:'service_cost_credits')
        self.service_cost_credits = attributes[:'service_cost_credits']
      else
        self.service_cost_credits = nil
      end

      if attributes.key?(:'total_cost_credits')
        self.total_cost_credits = attributes[:'total_cost_credits']
      else
        self.total_cost_credits = nil
      end

      if attributes.key?(:'successful_insights_count')
        self.successful_insights_count = attributes[:'successful_insights_count']
      else
        self.successful_insights_count = nil
      end

      if attributes.key?(:'failed_insights_count')
        self.failed_insights_count = attributes[:'failed_insights_count']
      else
        self.failed_insights_count = nil
      end

      if attributes.key?(:'generation_time_ms')
        self.generation_time_ms = attributes[:'generation_time_ms']
      end

      if attributes.key?(:'is_published')
        self.is_published = attributes[:'is_published']
      else
        self.is_published = nil
      end

      if attributes.key?(:'published_at')
        self.published_at = attributes[:'published_at']
      end

      if attributes.key?(:'view_count')
        self.view_count = attributes[:'view_count']
      else
        self.view_count = nil
      end

      if attributes.key?(:'last_edited_at')
        self.last_edited_at = attributes[:'last_edited_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @user_id.nil?
        invalid_properties.push('invalid value for "user_id", user_id cannot be nil.')
      end

      if @company_id.nil?
        invalid_properties.push('invalid value for "company_id", company_id cannot be nil.')
      end

      if @title.nil?
        invalid_properties.push('invalid value for "title", title cannot be nil.')
      end

      if @content_html.nil?
        invalid_properties.push('invalid value for "content_html", content_html cannot be nil.')
      end

      if @data_cost_credits.nil?
        invalid_properties.push('invalid value for "data_cost_credits", data_cost_credits cannot be nil.')
      end

      if @service_cost_credits.nil?
        invalid_properties.push('invalid value for "service_cost_credits", service_cost_credits cannot be nil.')
      end

      if @total_cost_credits.nil?
        invalid_properties.push('invalid value for "total_cost_credits", total_cost_credits cannot be nil.')
      end

      if @successful_insights_count.nil?
        invalid_properties.push('invalid value for "successful_insights_count", successful_insights_count cannot be nil.')
      end

      if @failed_insights_count.nil?
        invalid_properties.push('invalid value for "failed_insights_count", failed_insights_count cannot be nil.')
      end

      if @is_published.nil?
        invalid_properties.push('invalid value for "is_published", is_published cannot be nil.')
      end

      if @view_count.nil?
        invalid_properties.push('invalid value for "view_count", view_count cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @user_id.nil?
      return false if @company_id.nil?
      return false if @title.nil?
      return false if @content_html.nil?
      return false if @data_cost_credits.nil?
      return false if @service_cost_credits.nil?
      return false if @total_cost_credits.nil?
      return false if @successful_insights_count.nil?
      return false if @failed_insights_count.nil?
      return false if @is_published.nil?
      return false if @view_count.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] user_id Value to be assigned
    def user_id=(user_id)
      if user_id.nil?
        fail ArgumentError, 'user_id cannot be nil'
      end

      @user_id = user_id
    end

    # Custom attribute writer method with validation
    # @param [Object] company_id Value to be assigned
    def company_id=(company_id)
      if company_id.nil?
        fail ArgumentError, 'company_id cannot be nil'
      end

      @company_id = company_id
    end

    # Custom attribute writer method with validation
    # @param [Object] title Value to be assigned
    def title=(title)
      if title.nil?
        fail ArgumentError, 'title cannot be nil'
      end

      @title = title
    end

    # Custom attribute writer method with validation
    # @param [Object] content_html Value to be assigned
    def content_html=(content_html)
      if content_html.nil?
        fail ArgumentError, 'content_html cannot be nil'
      end

      @content_html = content_html
    end

    # Custom attribute writer method with validation
    # @param [Object] data_cost_credits Value to be assigned
    def data_cost_credits=(data_cost_credits)
      if data_cost_credits.nil?
        fail ArgumentError, 'data_cost_credits cannot be nil'
      end

      @data_cost_credits = data_cost_credits
    end

    # Custom attribute writer method with validation
    # @param [Object] service_cost_credits Value to be assigned
    def service_cost_credits=(service_cost_credits)
      if service_cost_credits.nil?
        fail ArgumentError, 'service_cost_credits cannot be nil'
      end

      @service_cost_credits = service_cost_credits
    end

    # Custom attribute writer method with validation
    # @param [Object] total_cost_credits Value to be assigned
    def total_cost_credits=(total_cost_credits)
      if total_cost_credits.nil?
        fail ArgumentError, 'total_cost_credits cannot be nil'
      end

      @total_cost_credits = total_cost_credits
    end

    # Custom attribute writer method with validation
    # @param [Object] successful_insights_count Value to be assigned
    def successful_insights_count=(successful_insights_count)
      if successful_insights_count.nil?
        fail ArgumentError, 'successful_insights_count cannot be nil'
      end

      @successful_insights_count = successful_insights_count
    end

    # Custom attribute writer method with validation
    # @param [Object] failed_insights_count Value to be assigned
    def failed_insights_count=(failed_insights_count)
      if failed_insights_count.nil?
        fail ArgumentError, 'failed_insights_count cannot be nil'
      end

      @failed_insights_count = failed_insights_count
    end

    # Custom attribute writer method with validation
    # @param [Object] is_published Value to be assigned
    def is_published=(is_published)
      if is_published.nil?
        fail ArgumentError, 'is_published cannot be nil'
      end

      @is_published = is_published
    end

    # Custom attribute writer method with validation
    # @param [Object] view_count Value to be assigned
    def view_count=(view_count)
      if view_count.nil?
        fail ArgumentError, 'view_count cannot be nil'
      end

      @view_count = view_count
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          date_created == o.date_created &&
          last_updated == o.last_updated &&
          post_id == o.post_id &&
          user_id == o.user_id &&
          company_id == o.company_id &&
          title == o.title &&
          category == o.category &&
          teaser == o.teaser &&
          content_html == o.content_html &&
          insights_used == o.insights_used &&
          generation_creativity == o.generation_creativity &&
          generation_target_word_count == o.generation_target_word_count &&
          generation_tone == o.generation_tone &&
          generation_include_citations == o.generation_include_citations &&
          generation_subheading_count == o.generation_subheading_count &&
          generation_temperature == o.generation_temperature &&
          data_cost_credits == o.data_cost_credits &&
          service_cost_credits == o.service_cost_credits &&
          total_cost_credits == o.total_cost_credits &&
          successful_insights_count == o.successful_insights_count &&
          failed_insights_count == o.failed_insights_count &&
          generation_time_ms == o.generation_time_ms &&
          is_published == o.is_published &&
          published_at == o.published_at &&
          view_count == o.view_count &&
          last_edited_at == o.last_edited_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [date_created, last_updated, post_id, user_id, company_id, title, category, teaser, content_html, insights_used, generation_creativity, generation_target_word_count, generation_tone, generation_include_citations, generation_subheading_count, generation_temperature, data_cost_credits, service_cost_credits, total_cost_credits, successful_insights_count, failed_insights_count, generation_time_ms, is_published, published_at, view_count, last_edited_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
