language: ruby
cache: bundler
rvm:
  - 2.7
  - 3.0
  - 3.1
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build spartera_api_sdk.gemspec
  - gem install ./spartera_api_sdk-1.0.69.gem
