# -*- encoding: utf-8 -*-

=begin
#Spartera API Documentation

#Auto-generated API documentation for REST services of the Spartera platform

The version of the OpenAPI document: 1.25.0
Contact: support@spartera.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "spartera_api_sdk/version"

Gem::Specification.new do |s|
  s.name        = "spartera_api_sdk"
  s.version     = SparteraApiSdk::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Spartera"]
  s.email       = ["tony@spartera.com"]
  s.homepage    = "https://github.com/spartera-com/spartera-ruby-sdk"
  s.summary     = "Spartera API Documentation Ruby Gem"
  s.description = "Auto-generated API documentation for REST services of the Spartera platform"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
