=begin
#Spartera API Documentation

#Auto-generated API documentation for REST services of the Spartera platform

The version of the OpenAPI document: 1.25.0
Contact: support@spartera.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::AssetPriceHistoryApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AssetPriceHistoryApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::AssetPriceHistoryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AssetPriceHistoryApi' do
    it 'should create an instance of AssetPriceHistoryApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::AssetPriceHistoryApi)
    end
  end

  # unit tests for create_asset_price_history
  # Create a new price history record for an asset
  # @param company_id Unique identifier for the Company
  # @param asset_id Unique identifier for the Asset
  # @param asset_price_history_input 
  # @param [Hash] opts the optional parameters
  # @return [CreateAssetPriceHistory200Response]
  describe 'create_asset_price_history test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_asset_price_history_prices_calculate_credits
  # Calculate the credit equivalent for a given USD price without saving
  # @param company_id Unique identifier for the Company
  # @param asset_id Unique identifier for the Asset
  # @param asset_price_history_input 
  # @param [Hash] opts the optional parameters
  # @return [CreateAssetPriceHistory200Response]
  describe 'create_asset_price_history_prices_calculate_credits test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_asset_price_history_prices_discount
  # POST /companies/{company_id}/assets/{asset_id}/prices/discount
  # @param company_id Unique identifier for the Company
  # @param asset_id Unique identifier for the Asset
  # @param asset_price_history_input 
  # @param [Hash] opts the optional parameters
  # @return [CreateAssetPriceHistory200Response]
  describe 'create_asset_price_history_prices_discount test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_asset_price_history
  # Delete single price history record by ID
  # @param company_id Unique identifier for the Company
  # @param asset_id Unique identifier for the Asset
  # @param aph_id Unique identifier for the Aph
  # @param [Hash] opts the optional parameters
  # @return [DeleteAssetPriceHistory200Response]
  describe 'delete_asset_price_history test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_asset_price_history_by_id
  # Get all price history records for a specific asset
  # @param company_id Unique identifier for the Company
  # @param asset_id Unique identifier for the Asset
  # @param [Hash] opts the optional parameters
  # @return [GetAssetPriceHistoryById200Response]
  describe 'get_asset_price_history_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_asset_price_history_by_id_assets_prices
  # Get single price history record by ID
  # @param company_id Unique identifier for the Company
  # @param asset_id Unique identifier for the Asset
  # @param aph_id Unique identifier for the Aph
  # @param [Hash] opts the optional parameters
  # @return [GetAssetPriceHistoryById200Response]
  describe 'get_asset_price_history_by_id_assets_prices test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_asset_price_history_by_id_prices_active
  # Get the currently active price for an asset
  # @param company_id Unique identifier for the Company
  # @param asset_id Unique identifier for the Asset
  # @param [Hash] opts the optional parameters
  # @return [GetAssetPriceHistoryById200Response]
  describe 'get_asset_price_history_by_id_prices_active test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_asset_price_history
  # Update an existing price history record by ID
  # @param company_id Unique identifier for the Company
  # @param asset_id Unique identifier for the Asset
  # @param aph_id Unique identifier for the Aph
  # @param asset_price_history_update 
  # @param [Hash] opts the optional parameters
  # @return [UpdateAssetPriceHistory200Response]
  describe 'update_asset_price_history test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
