=begin
#Spartera API Documentation

#Auto-generated API documentation for REST services of the Spartera platform

The version of the OpenAPI document: 0.0.0
Contact: support@spartera.com
Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SparteraApiSdk::AssetPriceHistoryApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AssetPriceHistoryApi' do
  before do
    # run before each test
    @api_instance = SparteraApiSdk::AssetPriceHistoryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AssetPriceHistoryApi' do
    it 'should create an instance of AssetPriceHistoryApi' do
      expect(@api_instance).to be_instance_of(SparteraApiSdk::AssetPriceHistoryApi)
    end
  end

  # unit tests for companies_company_id_assets_asset_id_prices_active_get
  # Get the currently active price for an asset
  # @param company_id 
  # @param asset_id 
  # @param [Hash] opts the optional parameters
  # @return [CompaniesCompanyIdApiKeysGet200Response]
  describe 'companies_company_id_assets_asset_id_prices_active_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for companies_company_id_assets_asset_id_prices_aph_id_delete
  # Delete single price history record by ID
  # @param company_id 
  # @param asset_id 
  # @param aph_id 
  # @param [Hash] opts the optional parameters
  # @return [CompaniesCompanyIdApiKeysGet200Response]
  describe 'companies_company_id_assets_asset_id_prices_aph_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for companies_company_id_assets_asset_id_prices_aph_id_get
  # Get single price history record by ID
  # @param company_id 
  # @param asset_id 
  # @param aph_id 
  # @param [Hash] opts the optional parameters
  # @return [CompaniesCompanyIdApiKeysGet200Response]
  describe 'companies_company_id_assets_asset_id_prices_aph_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for companies_company_id_assets_asset_id_prices_aph_id_patch
  # Update an existing price history record by ID
  # @param company_id 
  # @param asset_id 
  # @param aph_id 
  # @param [Hash] opts the optional parameters
  # @return [CompaniesCompanyIdApiKeysGet200Response]
  describe 'companies_company_id_assets_asset_id_prices_aph_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for companies_company_id_assets_asset_id_prices_calculate_credits_post
  # POST /companies/{company_id}/assets/{asset_id}/prices/calculate_credits
  # @param company_id 
  # @param asset_id 
  # @param [Hash] opts the optional parameters
  # @return [CompaniesCompanyIdApiKeysGet200Response]
  describe 'companies_company_id_assets_asset_id_prices_calculate_credits_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for companies_company_id_assets_asset_id_prices_discount_post
  # POST /companies/{company_id}/assets/{asset_id}/prices/discount
  # @param company_id 
  # @param asset_id 
  # @param [Hash] opts the optional parameters
  # @return [CompaniesCompanyIdApiKeysGet200Response]
  describe 'companies_company_id_assets_asset_id_prices_discount_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for companies_company_id_assets_asset_id_prices_get
  # Get all price history records for a specific asset
  # @param company_id 
  # @param asset_id 
  # @param [Hash] opts the optional parameters
  # @return [CompaniesCompanyIdApiKeysGet200Response]
  describe 'companies_company_id_assets_asset_id_prices_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for companies_company_id_assets_asset_id_prices_post
  # Create a new price history record for an asset
  # @param company_id 
  # @param asset_id 
  # @param [Hash] opts the optional parameters
  # @return [CompaniesCompanyIdApiKeysGet200Response]
  describe 'companies_company_id_assets_asset_id_prices_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
