=begin
#Spartera API Documentation

#Auto-generated API documentation for REST services of the Spartera platform

The version of the OpenAPI document: 0.0.0
Contact: support@spartera.com
Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SparteraApiSdk::CloudProvidersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CloudProvidersApi' do
  before do
    # run before each test
    @api_instance = SparteraApiSdk::CloudProvidersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CloudProvidersApi' do
    it 'should create an instance of CloudProvidersApi' do
      expect(@api_instance).to be_instance_of(SparteraApiSdk::CloudProvidersApi)
    end
  end

  # unit tests for cloud_providers_get
  # Get a list of all cloud providers
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'cloud_providers_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cloud_providers_post
  # Create single cloud provider
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'cloud_providers_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cloud_providers_provider_id_delete
  # Delete single cloud provider by ID
  # @param provider_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'cloud_providers_provider_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cloud_providers_provider_id_get
  # Get single cloud provider by ID
  # @param provider_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'cloud_providers_provider_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cloud_providers_provider_id_patch
  # Update an existing cloud provider by ID
  # @param provider_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'cloud_providers_provider_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
