=begin
#Spartera API Documentation

#Auto-generated API documentation for REST services of the Spartera platform

The version of the OpenAPI document: 0.0.0
Contact: support@spartera.com
Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SparteraApiSdk::ConnectionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ConnectionsApi' do
  before do
    # run before each test
    @api_instance = SparteraApiSdk::ConnectionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ConnectionsApi' do
    it 'should create an instance of ConnectionsApi' do
      expect(@api_instance).to be_instance_of(SparteraApiSdk::ConnectionsApi)
    end
  end

  # unit tests for companies_company_id_connections_connection_id_delete
  # Delete single connection by ID
  # @param company_id 
  # @param connection_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'companies_company_id_connections_connection_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for companies_company_id_connections_connection_id_get
  # Get single connection by ID
  # @param company_id 
  # @param connection_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'companies_company_id_connections_connection_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for companies_company_id_connections_connection_id_infoschema_get
  # Retrieve the information schema for the specified connection
  # @param company_id 
  # @param connection_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'companies_company_id_connections_connection_id_infoschema_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for companies_company_id_connections_connection_id_patch
  # Update an existing connection by ID
  # @param company_id 
  # @param connection_id 
  # @param connection 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'companies_company_id_connections_connection_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for companies_company_id_connections_connection_id_test_get
  # Verify the specified connection to ensure it is functioning correctly
  # @param company_id 
  # @param connection_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'companies_company_id_connections_connection_id_test_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for companies_company_id_connections_get
  # Get all connections for a specific company
  # @param company_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'companies_company_id_connections_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for companies_company_id_connections_post
  # Create a new connection by ID
  # @param company_id 
  # @param connection 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'companies_company_id_connections_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
