=begin
#Spartera API Documentation

#Auto-generated API documentation for REST services of the Spartera platform

The version of the OpenAPI document: 1.25.0
Contact: support@spartera.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SparteraApiSdk::EndpointsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EndpointsApi' do
  before do
    # run before each test
    @api_instance = SparteraApiSdk::EndpointsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EndpointsApi' do
    it 'should create an instance of EndpointsApi' do
      expect(@api_instance).to be_instance_of(SparteraApiSdk::EndpointsApi)
    end
  end

  # unit tests for create_endpoints
  # Create a new endpoint
  # @param company_id Unique identifier for the Company
  # @param endpoints_input 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number for pagination
  # @option opts [Integer] :limit Number of items per page
  # @option opts [String] :sort_by Field to sort by
  # @option opts [String] :sort_order Sort order (ascending or descending)
  # @option opts [String] :search Search term to filter results
  # @return [CreateEndpoints200Response]
  describe 'create_endpoints test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_endpoints_keys
  # POST /companies/{company_id}/endpoints/{endpoint_id}/keys
  # @param company_id Unique identifier for the Company
  # @param endpoint_id Unique identifier for the Endpoint
  # @param endpoints_input 
  # @param [Hash] opts the optional parameters
  # @return [CreateEndpoints200Response]
  describe 'create_endpoints_keys test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_endpoints
  # Delete single endpoint by ID
  # @param company_id Unique identifier for the Company
  # @param endpoint_id Unique identifier for the Endpoint
  # @param [Hash] opts the optional parameters
  # @return [DeleteEndpoints200Response]
  describe 'delete_endpoints test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_endpoints_keys
  # DELETE /companies/{company_id}/endpoints/{endpoint_id}/keys/{api_key_id}
  # @param company_id Unique identifier for the Company
  # @param endpoint_id Unique identifier for the Endpoint
  # @param api_key_id Unique identifier for the Api Key
  # @param [Hash] opts the optional parameters
  # @return [DeleteEndpoints200Response]
  describe 'delete_endpoints_keys test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_endpoints_by_id
  # Get single endpoint by ID
  # @param company_id Unique identifier for the Company
  # @param endpoint_id Unique identifier for the Endpoint
  # @param [Hash] opts the optional parameters
  # @return [GetEndpointsByIdConnectionsDescribe200Response]
  describe 'get_endpoints_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_endpoints_by_id_available_endpoints
  # GET /companies/{company_id}/endpoints/{endpoint_id}/available-endpoints
  # @param company_id Unique identifier for the Company
  # @param endpoint_id Unique identifier for the Endpoint
  # @param [Hash] opts the optional parameters
  # @return [GetEndpointsByIdConnectionsDescribe200Response]
  describe 'get_endpoints_by_id_available_endpoints test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_endpoints_by_id_connections_describe
  # Get schema information for a connection      Query parameters:         include_fields: Whether to include field information (default: true)         schemas: Optional comma-separated schemas to include         tables: Optional comma-separated tables to include
  # @param company_id Unique identifier for the Company
  # @param connection_id Unique identifier for the Connection
  # @param [Hash] opts the optional parameters
  # @return [GetEndpointsByIdConnectionsDescribe200Response]
  describe 'get_endpoints_by_id_connections_describe test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_endpoints_by_id_execute
  # Execute an endpoint with pagination support.      Customer-facing route that returns paginated data.     Query params: ?start&#x3D;0&amp;limit&#x3D;100
  # @param company_id Unique identifier for the Company
  # @param endpoint_id Unique identifier for the Endpoint
  # @param [Hash] opts the optional parameters
  # @return [GetEndpointsByIdConnectionsDescribe200Response]
  describe 'get_endpoints_by_id_execute test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_endpoints_by_id_keys
  # GET /companies/{company_id}/endpoints/{endpoint_id}/keys
  # @param company_id Unique identifier for the Company
  # @param endpoint_id Unique identifier for the Endpoint
  # @param [Hash] opts the optional parameters
  # @return [GetEndpointsByIdConnectionsDescribe200Response]
  describe 'get_endpoints_by_id_keys test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_endpoints_by_id_stats
  # Get usage statistics for an endpoint      Query parameters:         days: Number of days to analyze (default: 30)
  # @param company_id Unique identifier for the Company
  # @param endpoint_id Unique identifier for the Endpoint
  # @param [Hash] opts the optional parameters
  # @return [GetEndpointsByIdConnectionsDescribe200Response]
  describe 'get_endpoints_by_id_stats test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_endpoints_by_id_test
  # Test an endpoint with sample data      Request body (optional):         limit: Number of sample rows to return (default: 10)
  # @param company_id Unique identifier for the Company
  # @param endpoint_id Unique identifier for the Endpoint
  # @param [Hash] opts the optional parameters
  # @return [GetEndpointsByIdConnectionsDescribe200Response]
  describe 'get_endpoints_by_id_test test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_endpoints_by_id_url
  # GET /companies/{company_id}/endpoints/{endpoint_id}/url
  # @param company_id Unique identifier for the Company
  # @param endpoint_id Unique identifier for the Endpoint
  # @param [Hash] opts the optional parameters
  # @return [GetEndpointsByIdConnectionsDescribe200Response]
  describe 'get_endpoints_by_id_url test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_endpoints
  # Get all endpoints for a specific company with pagination, filtering, and sorting
  # @param company_id Unique identifier for the Company
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number for pagination
  # @option opts [Integer] :limit Number of items per page
  # @option opts [String] :sort_by Field to sort by
  # @option opts [String] :sort_order Sort order (ascending or descending)
  # @option opts [String] :search Search term to filter results
  # @return [ListEndpoints200Response]
  describe 'list_endpoints test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_endpoints
  # Update an existing endpoint by ID
  # @param company_id Unique identifier for the Company
  # @param endpoint_id Unique identifier for the Endpoint
  # @param endpoints_update 
  # @param [Hash] opts the optional parameters
  # @return [UpdateEndpoints200Response]
  describe 'update_endpoints test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
