=begin
#Spartera API Documentation

#Auto-generated API documentation for REST services of the Spartera platform

The version of the OpenAPI document: 1.25.0
Contact: support@spartera.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::IndustriesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'IndustriesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::IndustriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IndustriesApi' do
    it 'should create an instance of IndustriesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::IndustriesApi)
    end
  end

  # unit tests for get_industries_by_id
  # Get single industry by ID
  # @param industry_id Unique identifier for the Industry
  # @param [Hash] opts the optional parameters
  # @return [GetIndustriesById200Response]
  describe 'get_industries_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_industries
  # Get a list of all industries
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number for pagination
  # @option opts [Integer] :limit Number of items per page
  # @option opts [String] :sort_by Field to sort by
  # @option opts [String] :sort_order Sort order (ascending or descending)
  # @option opts [String] :search Search term to filter results
  # @return [ListIndustries200Response]
  describe 'list_industries test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_industries_active
  # Get a list of industries that have active marketplace products
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number for pagination
  # @option opts [Integer] :limit Number of items per page
  # @option opts [String] :sort_by Field to sort by
  # @option opts [String] :sort_order Sort order (ascending or descending)
  # @option opts [String] :search Search term to filter results
  # @return [ListIndustries200Response]
  describe 'list_industries_active test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
