=begin
#Spartera API Documentation

#Auto-generated API documentation for REST services of the Spartera platform

The version of the OpenAPI document: 1.25.0
Contact: support@spartera.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::PostgenIntegrationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PostgenIntegrationsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::PostgenIntegrationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PostgenIntegrationsApi' do
    it 'should create an instance of PostgenIntegrationsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::PostgenIntegrationsApi)
    end
  end

  # unit tests for create_postgen_integrations
  # POST /companies/{company_id}/postgen_integrations
  # @param company_id Unique identifier for the Company
  # @param postgen_integrations_input 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number for pagination
  # @option opts [Integer] :limit Number of items per page
  # @option opts [String] :sort_by Field to sort by
  # @option opts [String] :sort_order Sort order (ascending or descending)
  # @option opts [String] :search Search term to filter results
  # @return [CreatePostgenIntegrations200Response]
  describe 'create_postgen_integrations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_postgen_integrations_test
  # POST /companies/{company_id}/postgen_integrations/test
  # @param company_id Unique identifier for the Company
  # @param postgen_integrations_input 
  # @param [Hash] opts the optional parameters
  # @return [CreatePostgenIntegrations200Response]
  describe 'create_postgen_integrations_test test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_postgen_integrations
  # Delete single integration by ID.     Also deletes credentials from GCP Secret Manager.
  # @param company_id Unique identifier for the Company
  # @param integration_id Unique identifier for the Integration
  # @param [Hash] opts the optional parameters
  # @return [DeletePostgenIntegrations200Response]
  describe 'delete_postgen_integrations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_postgen_integrations_by_id
  # Get single integration by ID.
  # @param company_id Unique identifier for the Company
  # @param integration_id Unique identifier for the Integration
  # @param [Hash] opts the optional parameters
  # @return [GetPostgenIntegrationsById200Response]
  describe 'get_postgen_integrations_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_postgen_integrations
  # Get a list of all postgen integrations for the company.     All company users can view integrations.
  # @param company_id Unique identifier for the Company
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number for pagination
  # @option opts [Integer] :limit Number of items per page
  # @option opts [String] :sort_by Field to sort by
  # @option opts [String] :sort_order Sort order (ascending or descending)
  # @option opts [String] :search Search term to filter results
  # @return [ListPostgenIntegrations200Response]
  describe 'list_postgen_integrations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_postgen_integrations
  # Update an existing integration by ID.      Can update credentials, is_active status, etc.
  # @param company_id Unique identifier for the Company
  # @param integration_id Unique identifier for the Integration
  # @param postgen_integrations_update 
  # @param [Hash] opts the optional parameters
  # @return [UpdatePostgenIntegrations200Response]
  describe 'update_postgen_integrations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
