=begin
#Spartera API Documentation

#Auto-generated API documentation for REST services of the Spartera platform

The version of the OpenAPI document: 1.25.0
Contact: support@spartera.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::UsersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UsersApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::UsersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UsersApi' do
    it 'should create an instance of UsersApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::UsersApi)
    end
  end

  # unit tests for create_users
  # Create a new user
  # @param company_id Unique identifier for the Company
  # @param users_input 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number for pagination
  # @option opts [Integer] :limit Number of items per page
  # @option opts [String] :sort_by Field to sort by
  # @option opts [String] :sort_order Sort order (ascending or descending)
  # @option opts [String] :search Search term to filter results
  # @return [CreateUsers200Response]
  describe 'create_users test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_users_google_oauth
  # POST /companies/{company_id}/users/google-oauth
  # @param company_id Unique identifier for the Company
  # @param users_input 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number for pagination
  # @option opts [Integer] :limit Number of items per page
  # @option opts [String] :sort_by Field to sort by
  # @option opts [String] :sort_order Sort order (ascending or descending)
  # @option opts [String] :search Search term to filter results
  # @return [CreateUsers200Response]
  describe 'create_users_google_oauth test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_users_logout
  # Logout current user by revoking their sessions
  # @param company_id Unique identifier for the Company
  # @param users_input 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number for pagination
  # @option opts [Integer] :limit Number of items per page
  # @option opts [String] :sort_by Field to sort by
  # @option opts [String] :sort_order Sort order (ascending or descending)
  # @option opts [String] :search Search term to filter results
  # @return [CreateUsers200Response]
  describe 'create_users_logout test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_users
  # Delete single user by ID
  # @param company_id Unique identifier for the Company
  # @param user_id Unique identifier for the User
  # @param [Hash] opts the optional parameters
  # @return [DeleteUsers200Response]
  describe 'delete_users test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_users_by_id
  # Get single user by ID
  # @param company_id Unique identifier for the Company
  # @param user_id Unique identifier for the User
  # @param [Hash] opts the optional parameters
  # @return [GetUsersById200Response]
  describe 'get_users_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_users
  # Get a list of all users in a company
  # @param company_id Unique identifier for the Company
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number for pagination
  # @option opts [Integer] :limit Number of items per page
  # @option opts [String] :sort_by Field to sort by
  # @option opts [String] :sort_order Sort order (ascending or descending)
  # @option opts [String] :search Search term to filter results
  # @return [ListUsers200Response]
  describe 'list_users test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_users_me
  # Get current authenticated user&#39;s profile.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number for pagination
  # @option opts [Integer] :limit Number of items per page
  # @option opts [String] :sort_by Field to sort by
  # @option opts [String] :sort_order Sort order (ascending or descending)
  # @option opts [String] :search Search term to filter results
  # @return [ListUsers200Response]
  describe 'list_users_me test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_users
  # Update an existing user by ID
  # @param company_id Unique identifier for the Company
  # @param user_id Unique identifier for the User
  # @param users_update 
  # @param [Hash] opts the optional parameters
  # @return [UpdateUsers200Response]
  describe 'update_users test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
