=begin
#Spartera API Documentation

#Auto-generated API documentation for REST services of the Spartera platform

The version of the OpenAPI document: 1.25.0
Contact: support@spartera.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SparteraApiSdk::StorageEngines
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SparteraApiSdk::StorageEngines do
  #let(:instance) { SparteraApiSdk::StorageEngines.new }

  describe 'test an instance of StorageEngines' do
    it 'should create an instance of StorageEngines' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(SparteraApiSdk::StorageEngines)
    end
  end

  describe 'test attribute "date_created"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "last_updated"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "engine_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "provider_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "service_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "engine_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["EDW", "LLM", "RDBMS", "OBJ", "API_MODEL", "EXTERNAL_API"])
      # validator.allowable_values.each do |value|
      #   expect { instance.engine_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "integration_complete"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "test_func_complete"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
