=begin
#Spartera API Documentation

#Auto-generated API documentation for REST services of the Spartera platform

The version of the OpenAPI document: 1.25.0
Contact: support@spartera.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SparteraApiSdk::UpdateAssets200ResponseData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SparteraApiSdk::UpdateAssets200ResponseData do
  #let(:instance) { SparteraApiSdk::UpdateAssets200ResponseData.new }

  describe 'test an instance of UpdateAssets200ResponseData' do
    it 'should create an instance of UpdateAssets200ResponseData' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(SparteraApiSdk::UpdateAssets200ResponseData)
    end
  end

  describe 'test attribute "asset_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
