=begin
#Spartera API Documentation

#Auto-generated API documentation for REST services of the Spartera platform

The version of the OpenAPI document: 1.25.0
Contact: support@spartera.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module SparteraApiSdk
  # Secure connections from Spartera to your databases and data warehouses
  class Connections < ApiModelBase
    # Optional.
    attr_accessor :date_created

    # Optional.
    attr_accessor :last_updated

    # Unique identifier.
    attr_accessor :connection_id

    # References users.user_id — An individual user account within a company. See GET /users for valid values. Optional.
    attr_accessor :user_id

    # References storage_engines.engine_id — Fact table of all the different storage engines we support. See GET /storage_engines for valid values. Required.
    attr_accessor :engine_id

    # References companies.company_id — A Spartera seller or buyer company account. See GET /companies for valid values. Required.
    attr_accessor :company_id

    # Optional. One of: SERVICE_ACCOUNT, USERNAME_PASSWORD, API_KEY, SERVICE_IDENTITY, ACCESS_KEY, … (10 total).
    attr_accessor :credential_type

    # Optional.
    attr_accessor :name

    # Optional.
    attr_accessor :description

    # Domain of the external API provider (e.g., 'api.weather.com')
    attr_accessor :provider_domain

    # Optional.
    attr_accessor :verified_usage_ability

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'date_created' => :'date_created',
        :'last_updated' => :'last_updated',
        :'connection_id' => :'connection_id',
        :'user_id' => :'user_id',
        :'engine_id' => :'engine_id',
        :'company_id' => :'company_id',
        :'credential_type' => :'credential_type',
        :'name' => :'name',
        :'description' => :'description',
        :'provider_domain' => :'provider_domain',
        :'verified_usage_ability' => :'verified_usage_ability'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'date_created' => :'Time',
        :'last_updated' => :'Time',
        :'connection_id' => :'String',
        :'user_id' => :'String',
        :'engine_id' => :'Integer',
        :'company_id' => :'String',
        :'credential_type' => :'String',
        :'name' => :'String',
        :'description' => :'String',
        :'provider_domain' => :'String',
        :'verified_usage_ability' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SparteraApiSdk::Connections` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SparteraApiSdk::Connections`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'date_created')
        self.date_created = attributes[:'date_created']
      end

      if attributes.key?(:'last_updated')
        self.last_updated = attributes[:'last_updated']
      end

      if attributes.key?(:'connection_id')
        self.connection_id = attributes[:'connection_id']
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      end

      if attributes.key?(:'engine_id')
        self.engine_id = attributes[:'engine_id']
      else
        self.engine_id = nil
      end

      if attributes.key?(:'company_id')
        self.company_id = attributes[:'company_id']
      else
        self.company_id = nil
      end

      if attributes.key?(:'credential_type')
        self.credential_type = attributes[:'credential_type']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'provider_domain')
        self.provider_domain = attributes[:'provider_domain']
      end

      if attributes.key?(:'verified_usage_ability')
        self.verified_usage_ability = attributes[:'verified_usage_ability']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @engine_id.nil?
        invalid_properties.push('invalid value for "engine_id", engine_id cannot be nil.')
      end

      if @company_id.nil?
        invalid_properties.push('invalid value for "company_id", company_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @engine_id.nil?
      return false if @company_id.nil?
      credential_type_validator = EnumAttributeValidator.new('String', ["SERVICE_ACCOUNT", "USERNAME_PASSWORD", "API_KEY", "SERVICE_IDENTITY", "ACCESS_KEY", "NONE", "OAUTH", "JSON", "KEY_PAIR", "CLIENT_SECRET"])
      return false unless credential_type_validator.valid?(@credential_type)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] engine_id Value to be assigned
    def engine_id=(engine_id)
      if engine_id.nil?
        fail ArgumentError, 'engine_id cannot be nil'
      end

      @engine_id = engine_id
    end

    # Custom attribute writer method with validation
    # @param [Object] company_id Value to be assigned
    def company_id=(company_id)
      if company_id.nil?
        fail ArgumentError, 'company_id cannot be nil'
      end

      @company_id = company_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] credential_type Object to be assigned
    def credential_type=(credential_type)
      validator = EnumAttributeValidator.new('String', ["SERVICE_ACCOUNT", "USERNAME_PASSWORD", "API_KEY", "SERVICE_IDENTITY", "ACCESS_KEY", "NONE", "OAUTH", "JSON", "KEY_PAIR", "CLIENT_SECRET"])
      unless validator.valid?(credential_type)
        fail ArgumentError, "invalid value for \"credential_type\", must be one of #{validator.allowable_values}."
      end
      @credential_type = credential_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          date_created == o.date_created &&
          last_updated == o.last_updated &&
          connection_id == o.connection_id &&
          user_id == o.user_id &&
          engine_id == o.engine_id &&
          company_id == o.company_id &&
          credential_type == o.credential_type &&
          name == o.name &&
          description == o.description &&
          provider_domain == o.provider_domain &&
          verified_usage_ability == o.verified_usage_ability
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [date_created, last_updated, connection_id, user_id, engine_id, company_id, credential_type, name, description, provider_domain, verified_usage_ability].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
