=begin
#Spartera API Documentation

#Auto-generated API documentation for REST services of the Spartera platform

The version of the OpenAPI document: 1.25.0
Contact: support@spartera.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module SparteraApiSdk
  # Update schema for modifying Endpoint
  class EndpointsUpdate < ApiModelBase
    # Required.
    attr_accessor :date_created

    # Required.
    attr_accessor :last_updated

    # User who created this endpoint
    attr_accessor :user_id

    # References companies.company_id — A Spartera seller or buyer company account. See GET /companies for valid values. Required.
    attr_accessor :company_id

    # Connection to the data source
    attr_accessor :connection_id

    # Industry / category for marketplace discovery
    attr_accessor :industry_id

    # Primary use case for marketplace discovery
    attr_accessor :auc_id

    # Approval status before marketplace publication
    attr_accessor :approval_status

    # User who approved this endpoint for marketplace
    attr_accessor :approved_by_user_id

    # Timestamp of marketplace approval
    attr_accessor :approved_at

    # Whether this endpoint appears in the public marketplace
    attr_accessor :sell_in_marketplace

    # Human-readable name for the endpoint
    attr_accessor :name

    # Human-readable, URL-safe slug derived from name at creation time. e.g. 'NFL Live Moneyline & Spread Odds' → 'nfl-live-moneyline-spread-odds'. Never changes after creation. Unique within company (DB constraint). Creation fails with 409 if a duplicate name exists in the same company.
    attr_accessor :slug

    # Description of what this endpoint provides
    attr_accessor :description

    # Long-form HTML description for product pages and SEO
    attr_accessor :detailed_description

    # Top 3 questions this endpoint can help answer, in English. Stored as JSON array of strings (1-3 items, 15-200 chars each). Strongly encouraged for marketplace endpoints but not required — nudge via UI completeness score, not hard validation.
    attr_accessor :top_questions

    # Schema/database name where the table resides
    attr_accessor :source_schema_name

    # Table name to query from
    attr_accessor :source_table_name

    # Named customer for B2B deals (pricing handled via asset_price_history)
    attr_accessor :customer_name

    # Column configurations including aggregations, filters, and visibility. Format: {columns: [{name, type, aggregation, filter, is_hidden, alias, ...}]}. This is the source of truth — SQL is generated at runtime from this configuration.
    attr_accessor :endpoint_schema

    # Number of requests allowed per rate_limit_period
    attr_accessor :rate_limit_number

    # Time period for rate limiting (HOUR, DAY, MONTH)
    attr_accessor :rate_limit_period

    # How to group rate limits (IP, USER, COMPANY, API_KEY, GLOBAL)
    attr_accessor :rate_limit_granularity

    # Access control method (OPEN, API_KEY, IP, EMAIL, DOMAIN)
    attr_accessor :access_method

    # List of allowed IPs, emails, or domains based on access_method. Format: {type: 'ip'|'email'|'domain', values: ['192.168.1.1', ...]}
    attr_accessor :access_whitelist

    # Current status of the endpoint (ACTIVE, INACTIVE, DEPRECATED)
    attr_accessor :status

    # Start date of the data time period covered
    attr_accessor :data_time_period_start

    # End date of the data time period covered
    attr_accessor :data_time_period_end

    # When the seller began actively collecting this data. Distinct from data_time_period_start, which describes when the records themselves begin. Backfilled historical data will have date_collection_start > data_time_period_start.
    attr_accessor :date_collection_start

    # Type of geographic coverage
    attr_accessor :geographic_coverage_type

    # Specific regions/countries covered (e.g., 'United States, Canada, Mexico')
    attr_accessor :geographic_coverage_details

    # How often the source data is refreshed
    attr_accessor :data_source_refresh_frequency

    # Comma-separated tags for organizing endpoints
    attr_accessor :tags

    # When this endpoint was last called
    attr_accessor :last_accessed

    # Seller-enforced row cap per request. Buyers cannot exceed this. Default 1000.
    attr_accessor :max_records_per_request

    # Whether this endpoint supports bulk export to GCS. When True, buyers can request delivery=gcs with format=csv|parquet. Independent of max_records_per_request, which only governs inline JSON.
    attr_accessor :export_enabled

    # Hard ceiling on rows returned per GCS export. Separate from max_records_per_request so sellers can offer larger downloads via file delivery without expanding inline JSON responses.
    attr_accessor :max_records_per_export

    # Last successful {spartera, request, response} envelope. Saved on each successful marketplace run. Displayed as preview on product page load.
    attr_accessor :sample_response

    # Required.
    attr_accessor :active

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'date_created' => :'date_created',
        :'last_updated' => :'last_updated',
        :'user_id' => :'user_id',
        :'company_id' => :'company_id',
        :'connection_id' => :'connection_id',
        :'industry_id' => :'industry_id',
        :'auc_id' => :'auc_id',
        :'approval_status' => :'approval_status',
        :'approved_by_user_id' => :'approved_by_user_id',
        :'approved_at' => :'approved_at',
        :'sell_in_marketplace' => :'sell_in_marketplace',
        :'name' => :'name',
        :'slug' => :'slug',
        :'description' => :'description',
        :'detailed_description' => :'detailed_description',
        :'top_questions' => :'top_questions',
        :'source_schema_name' => :'source_schema_name',
        :'source_table_name' => :'source_table_name',
        :'customer_name' => :'customer_name',
        :'endpoint_schema' => :'endpoint_schema',
        :'rate_limit_number' => :'rate_limit_number',
        :'rate_limit_period' => :'rate_limit_period',
        :'rate_limit_granularity' => :'rate_limit_granularity',
        :'access_method' => :'access_method',
        :'access_whitelist' => :'access_whitelist',
        :'status' => :'status',
        :'data_time_period_start' => :'data_time_period_start',
        :'data_time_period_end' => :'data_time_period_end',
        :'date_collection_start' => :'date_collection_start',
        :'geographic_coverage_type' => :'geographic_coverage_type',
        :'geographic_coverage_details' => :'geographic_coverage_details',
        :'data_source_refresh_frequency' => :'data_source_refresh_frequency',
        :'tags' => :'tags',
        :'last_accessed' => :'last_accessed',
        :'max_records_per_request' => :'max_records_per_request',
        :'export_enabled' => :'export_enabled',
        :'max_records_per_export' => :'max_records_per_export',
        :'sample_response' => :'sample_response',
        :'active' => :'active'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'date_created' => :'Time',
        :'last_updated' => :'Time',
        :'user_id' => :'String',
        :'company_id' => :'String',
        :'connection_id' => :'String',
        :'industry_id' => :'Integer',
        :'auc_id' => :'Integer',
        :'approval_status' => :'String',
        :'approved_by_user_id' => :'String',
        :'approved_at' => :'Time',
        :'sell_in_marketplace' => :'Boolean',
        :'name' => :'String',
        :'slug' => :'String',
        :'description' => :'String',
        :'detailed_description' => :'String',
        :'top_questions' => :'String',
        :'source_schema_name' => :'String',
        :'source_table_name' => :'String',
        :'customer_name' => :'String',
        :'endpoint_schema' => :'Object',
        :'rate_limit_number' => :'Integer',
        :'rate_limit_period' => :'String',
        :'rate_limit_granularity' => :'String',
        :'access_method' => :'String',
        :'access_whitelist' => :'Object',
        :'status' => :'String',
        :'data_time_period_start' => :'Time',
        :'data_time_period_end' => :'Time',
        :'date_collection_start' => :'Time',
        :'geographic_coverage_type' => :'String',
        :'geographic_coverage_details' => :'String',
        :'data_source_refresh_frequency' => :'String',
        :'tags' => :'String',
        :'last_accessed' => :'Time',
        :'max_records_per_request' => :'Integer',
        :'export_enabled' => :'Boolean',
        :'max_records_per_export' => :'Integer',
        :'sample_response' => :'Object',
        :'active' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SparteraApiSdk::EndpointsUpdate` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SparteraApiSdk::EndpointsUpdate`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'date_created')
        self.date_created = attributes[:'date_created']
      end

      if attributes.key?(:'last_updated')
        self.last_updated = attributes[:'last_updated']
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      end

      if attributes.key?(:'company_id')
        self.company_id = attributes[:'company_id']
      end

      if attributes.key?(:'connection_id')
        self.connection_id = attributes[:'connection_id']
      end

      if attributes.key?(:'industry_id')
        self.industry_id = attributes[:'industry_id']
      end

      if attributes.key?(:'auc_id')
        self.auc_id = attributes[:'auc_id']
      end

      if attributes.key?(:'approval_status')
        self.approval_status = attributes[:'approval_status']
      end

      if attributes.key?(:'approved_by_user_id')
        self.approved_by_user_id = attributes[:'approved_by_user_id']
      end

      if attributes.key?(:'approved_at')
        self.approved_at = attributes[:'approved_at']
      end

      if attributes.key?(:'sell_in_marketplace')
        self.sell_in_marketplace = attributes[:'sell_in_marketplace']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'slug')
        self.slug = attributes[:'slug']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'detailed_description')
        self.detailed_description = attributes[:'detailed_description']
      end

      if attributes.key?(:'top_questions')
        self.top_questions = attributes[:'top_questions']
      end

      if attributes.key?(:'source_schema_name')
        self.source_schema_name = attributes[:'source_schema_name']
      end

      if attributes.key?(:'source_table_name')
        self.source_table_name = attributes[:'source_table_name']
      end

      if attributes.key?(:'customer_name')
        self.customer_name = attributes[:'customer_name']
      end

      if attributes.key?(:'endpoint_schema')
        self.endpoint_schema = attributes[:'endpoint_schema']
      end

      if attributes.key?(:'rate_limit_number')
        self.rate_limit_number = attributes[:'rate_limit_number']
      end

      if attributes.key?(:'rate_limit_period')
        self.rate_limit_period = attributes[:'rate_limit_period']
      end

      if attributes.key?(:'rate_limit_granularity')
        self.rate_limit_granularity = attributes[:'rate_limit_granularity']
      end

      if attributes.key?(:'access_method')
        self.access_method = attributes[:'access_method']
      end

      if attributes.key?(:'access_whitelist')
        self.access_whitelist = attributes[:'access_whitelist']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'data_time_period_start')
        self.data_time_period_start = attributes[:'data_time_period_start']
      end

      if attributes.key?(:'data_time_period_end')
        self.data_time_period_end = attributes[:'data_time_period_end']
      end

      if attributes.key?(:'date_collection_start')
        self.date_collection_start = attributes[:'date_collection_start']
      end

      if attributes.key?(:'geographic_coverage_type')
        self.geographic_coverage_type = attributes[:'geographic_coverage_type']
      end

      if attributes.key?(:'geographic_coverage_details')
        self.geographic_coverage_details = attributes[:'geographic_coverage_details']
      end

      if attributes.key?(:'data_source_refresh_frequency')
        self.data_source_refresh_frequency = attributes[:'data_source_refresh_frequency']
      end

      if attributes.key?(:'tags')
        self.tags = attributes[:'tags']
      end

      if attributes.key?(:'last_accessed')
        self.last_accessed = attributes[:'last_accessed']
      end

      if attributes.key?(:'max_records_per_request')
        self.max_records_per_request = attributes[:'max_records_per_request']
      end

      if attributes.key?(:'export_enabled')
        self.export_enabled = attributes[:'export_enabled']
      end

      if attributes.key?(:'max_records_per_export')
        self.max_records_per_export = attributes[:'max_records_per_export']
      end

      if attributes.key?(:'sample_response')
        self.sample_response = attributes[:'sample_response']
      end

      if attributes.key?(:'active')
        self.active = attributes[:'active']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      approval_status_validator = EnumAttributeValidator.new('String', ["PENDING", "APPROVED", "REJECTED", "NEEDS_REVISION"])
      return false unless approval_status_validator.valid?(@approval_status)
      rate_limit_period_validator = EnumAttributeValidator.new('String', ["SECOND", "MINUTE", "HOUR", "DAY"])
      return false unless rate_limit_period_validator.valid?(@rate_limit_period)
      rate_limit_granularity_validator = EnumAttributeValidator.new('String', ["USER", "COMPANY", "IP", "GLOBAL"])
      return false unless rate_limit_granularity_validator.valid?(@rate_limit_granularity)
      access_method_validator = EnumAttributeValidator.new('String', ["OPEN", "API_KEY", "IP", "EMAIL", "DOMAIN"])
      return false unless access_method_validator.valid?(@access_method)
      status_validator = EnumAttributeValidator.new('String', ["ACTIVE", "INACTIVE", "DEPRECATED"])
      return false unless status_validator.valid?(@status)
      geographic_coverage_type_validator = EnumAttributeValidator.new('String', ["GLOBAL", "CONTINENTAL", "REGIONAL", "NATIONAL", "STATE", "LOCAL", "CUSTOM", "UNKNOWN"])
      return false unless geographic_coverage_type_validator.valid?(@geographic_coverage_type)
      data_source_refresh_frequency_validator = EnumAttributeValidator.new('String', ["EVERY_SECOND", "EVERY_MINUTE", "EVERY_HOUR", "EVERY_DAY", "EVERY_WEEK", "EVERY_MONTH", "EVERY_QUARTER", "EVERY_YEAR", "NEVER", "UNKNOWN"])
      return false unless data_source_refresh_frequency_validator.valid?(@data_source_refresh_frequency)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] approval_status Object to be assigned
    def approval_status=(approval_status)
      validator = EnumAttributeValidator.new('String', ["PENDING", "APPROVED", "REJECTED", "NEEDS_REVISION"])
      unless validator.valid?(approval_status)
        fail ArgumentError, "invalid value for \"approval_status\", must be one of #{validator.allowable_values}."
      end
      @approval_status = approval_status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] rate_limit_period Object to be assigned
    def rate_limit_period=(rate_limit_period)
      validator = EnumAttributeValidator.new('String', ["SECOND", "MINUTE", "HOUR", "DAY"])
      unless validator.valid?(rate_limit_period)
        fail ArgumentError, "invalid value for \"rate_limit_period\", must be one of #{validator.allowable_values}."
      end
      @rate_limit_period = rate_limit_period
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] rate_limit_granularity Object to be assigned
    def rate_limit_granularity=(rate_limit_granularity)
      validator = EnumAttributeValidator.new('String', ["USER", "COMPANY", "IP", "GLOBAL"])
      unless validator.valid?(rate_limit_granularity)
        fail ArgumentError, "invalid value for \"rate_limit_granularity\", must be one of #{validator.allowable_values}."
      end
      @rate_limit_granularity = rate_limit_granularity
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] access_method Object to be assigned
    def access_method=(access_method)
      validator = EnumAttributeValidator.new('String', ["OPEN", "API_KEY", "IP", "EMAIL", "DOMAIN"])
      unless validator.valid?(access_method)
        fail ArgumentError, "invalid value for \"access_method\", must be one of #{validator.allowable_values}."
      end
      @access_method = access_method
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["ACTIVE", "INACTIVE", "DEPRECATED"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] geographic_coverage_type Object to be assigned
    def geographic_coverage_type=(geographic_coverage_type)
      validator = EnumAttributeValidator.new('String', ["GLOBAL", "CONTINENTAL", "REGIONAL", "NATIONAL", "STATE", "LOCAL", "CUSTOM", "UNKNOWN"])
      unless validator.valid?(geographic_coverage_type)
        fail ArgumentError, "invalid value for \"geographic_coverage_type\", must be one of #{validator.allowable_values}."
      end
      @geographic_coverage_type = geographic_coverage_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] data_source_refresh_frequency Object to be assigned
    def data_source_refresh_frequency=(data_source_refresh_frequency)
      validator = EnumAttributeValidator.new('String', ["EVERY_SECOND", "EVERY_MINUTE", "EVERY_HOUR", "EVERY_DAY", "EVERY_WEEK", "EVERY_MONTH", "EVERY_QUARTER", "EVERY_YEAR", "NEVER", "UNKNOWN"])
      unless validator.valid?(data_source_refresh_frequency)
        fail ArgumentError, "invalid value for \"data_source_refresh_frequency\", must be one of #{validator.allowable_values}."
      end
      @data_source_refresh_frequency = data_source_refresh_frequency
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          date_created == o.date_created &&
          last_updated == o.last_updated &&
          user_id == o.user_id &&
          company_id == o.company_id &&
          connection_id == o.connection_id &&
          industry_id == o.industry_id &&
          auc_id == o.auc_id &&
          approval_status == o.approval_status &&
          approved_by_user_id == o.approved_by_user_id &&
          approved_at == o.approved_at &&
          sell_in_marketplace == o.sell_in_marketplace &&
          name == o.name &&
          slug == o.slug &&
          description == o.description &&
          detailed_description == o.detailed_description &&
          top_questions == o.top_questions &&
          source_schema_name == o.source_schema_name &&
          source_table_name == o.source_table_name &&
          customer_name == o.customer_name &&
          endpoint_schema == o.endpoint_schema &&
          rate_limit_number == o.rate_limit_number &&
          rate_limit_period == o.rate_limit_period &&
          rate_limit_granularity == o.rate_limit_granularity &&
          access_method == o.access_method &&
          access_whitelist == o.access_whitelist &&
          status == o.status &&
          data_time_period_start == o.data_time_period_start &&
          data_time_period_end == o.data_time_period_end &&
          date_collection_start == o.date_collection_start &&
          geographic_coverage_type == o.geographic_coverage_type &&
          geographic_coverage_details == o.geographic_coverage_details &&
          data_source_refresh_frequency == o.data_source_refresh_frequency &&
          tags == o.tags &&
          last_accessed == o.last_accessed &&
          max_records_per_request == o.max_records_per_request &&
          export_enabled == o.export_enabled &&
          max_records_per_export == o.max_records_per_export &&
          sample_response == o.sample_response &&
          active == o.active
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [date_created, last_updated, user_id, company_id, connection_id, industry_id, auc_id, approval_status, approved_by_user_id, approved_at, sell_in_marketplace, name, slug, description, detailed_description, top_questions, source_schema_name, source_table_name, customer_name, endpoint_schema, rate_limit_number, rate_limit_period, rate_limit_granularity, access_method, access_whitelist, status, data_time_period_start, data_time_period_end, date_collection_start, geographic_coverage_type, geographic_coverage_details, data_source_refresh_frequency, tags, last_accessed, max_records_per_request, export_enabled, max_records_per_export, sample_response, active].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
