=begin
#Spartera API Documentation

#Auto-generated API documentation for REST services of the Spartera platform

The version of the OpenAPI document: 1.25.0
Contact: support@spartera.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module SparteraApiSdk
  # An individual user account within a company
  class Users < ApiModelBase
    # Optional.
    attr_accessor :date_created

    # Optional.
    attr_accessor :last_updated

    # Unique identifier.
    attr_accessor :user_id

    # References companies.company_id — A Spartera seller or buyer company account. See GET /companies for valid values. Required.
    attr_accessor :company_id

    # User's role for RBAC - single source of truth
    attr_accessor :role_id

    # User's job function/title
    attr_accessor :function_id

    # Required. One of: ACTIVE, PENDING, INACTIVE, BANNED.
    attr_accessor :status

    # Optional. Must be unique.
    attr_accessor :email_address

    # Optional.
    attr_accessor :timezone

    # Whether user has opted out of marketing communications. Default false = opted in per ToS.
    attr_accessor :marketing_opt_out

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'date_created' => :'date_created',
        :'last_updated' => :'last_updated',
        :'user_id' => :'user_id',
        :'company_id' => :'company_id',
        :'role_id' => :'role_id',
        :'function_id' => :'function_id',
        :'status' => :'status',
        :'email_address' => :'email_address',
        :'timezone' => :'timezone',
        :'marketing_opt_out' => :'marketing_opt_out'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'date_created' => :'Time',
        :'last_updated' => :'Time',
        :'user_id' => :'String',
        :'company_id' => :'String',
        :'role_id' => :'Integer',
        :'function_id' => :'Integer',
        :'status' => :'String',
        :'email_address' => :'String',
        :'timezone' => :'String',
        :'marketing_opt_out' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `SparteraApiSdk::Users` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `SparteraApiSdk::Users`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'date_created')
        self.date_created = attributes[:'date_created']
      end

      if attributes.key?(:'last_updated')
        self.last_updated = attributes[:'last_updated']
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      end

      if attributes.key?(:'company_id')
        self.company_id = attributes[:'company_id']
      else
        self.company_id = nil
      end

      if attributes.key?(:'role_id')
        self.role_id = attributes[:'role_id']
      else
        self.role_id = nil
      end

      if attributes.key?(:'function_id')
        self.function_id = attributes[:'function_id']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'email_address')
        self.email_address = attributes[:'email_address']
      end

      if attributes.key?(:'timezone')
        self.timezone = attributes[:'timezone']
      end

      if attributes.key?(:'marketing_opt_out')
        self.marketing_opt_out = attributes[:'marketing_opt_out']
      else
        self.marketing_opt_out = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @company_id.nil?
        invalid_properties.push('invalid value for "company_id", company_id cannot be nil.')
      end

      if @role_id.nil?
        invalid_properties.push('invalid value for "role_id", role_id cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @marketing_opt_out.nil?
        invalid_properties.push('invalid value for "marketing_opt_out", marketing_opt_out cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @company_id.nil?
      return false if @role_id.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["ACTIVE", "PENDING", "INACTIVE", "BANNED"])
      return false unless status_validator.valid?(@status)
      return false if @marketing_opt_out.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] company_id Value to be assigned
    def company_id=(company_id)
      if company_id.nil?
        fail ArgumentError, 'company_id cannot be nil'
      end

      @company_id = company_id
    end

    # Custom attribute writer method with validation
    # @param [Object] role_id Value to be assigned
    def role_id=(role_id)
      if role_id.nil?
        fail ArgumentError, 'role_id cannot be nil'
      end

      @role_id = role_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["ACTIVE", "PENDING", "INACTIVE", "BANNED"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] marketing_opt_out Value to be assigned
    def marketing_opt_out=(marketing_opt_out)
      if marketing_opt_out.nil?
        fail ArgumentError, 'marketing_opt_out cannot be nil'
      end

      @marketing_opt_out = marketing_opt_out
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          date_created == o.date_created &&
          last_updated == o.last_updated &&
          user_id == o.user_id &&
          company_id == o.company_id &&
          role_id == o.role_id &&
          function_id == o.function_id &&
          status == o.status &&
          email_address == o.email_address &&
          timezone == o.timezone &&
          marketing_opt_out == o.marketing_opt_out
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [date_created, last_updated, user_id, company_id, role_id, function_id, status, email_address, timezone, marketing_opt_out].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
