=begin
#Spartera API Documentation

#Auto-generated API documentation for REST services of the Spartera platform

The version of the OpenAPI document: 0.0.0
Contact: support@spartera.com
Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

# Common files
require 'spartera_api_sdk/api_client'
require 'spartera_api_sdk/api_error'
require 'spartera_api_sdk/version'
require 'spartera_api_sdk/configuration'

# Models
require 'spartera_api_sdk/models/alert'
require 'spartera_api_sdk/models/apikey'
require 'spartera_api_sdk/models/asset'
require 'spartera_api_sdk/models/assetpricehistory'
require 'spartera_api_sdk/models/cloudprovider'
require 'spartera_api_sdk/models/companies_company_id_api_keys_get200_response'
require 'spartera_api_sdk/models/companies_company_id_assets_asset_id_delete200_response'
require 'spartera_api_sdk/models/companies_company_id_assets_asset_id_delete200_response_data'
require 'spartera_api_sdk/models/companies_company_id_assets_asset_id_get200_response'
require 'spartera_api_sdk/models/companies_company_id_assets_asset_id_patch200_response'
require 'spartera_api_sdk/models/companies_company_id_assets_asset_id_patch200_response_data'
require 'spartera_api_sdk/models/companies_company_id_assets_get200_response'
require 'spartera_api_sdk/models/companies_company_id_assets_post200_response'
require 'spartera_api_sdk/models/companies_company_id_assets_post200_response_data'
require 'spartera_api_sdk/models/companies_company_id_connections_connection_id_delete200_response'
require 'spartera_api_sdk/models/companies_company_id_connections_connection_id_delete200_response_data'
require 'spartera_api_sdk/models/companies_company_id_connections_connection_id_get200_response'
require 'spartera_api_sdk/models/companies_company_id_connections_connection_id_patch200_response'
require 'spartera_api_sdk/models/companies_company_id_connections_connection_id_patch200_response_data'
require 'spartera_api_sdk/models/companies_company_id_connections_get200_response'
require 'spartera_api_sdk/models/companies_company_id_connections_post200_response'
require 'spartera_api_sdk/models/companies_company_id_connections_post200_response_data'
require 'spartera_api_sdk/models/companies_company_id_users_get200_response'
require 'spartera_api_sdk/models/companies_company_id_users_post200_response'
require 'spartera_api_sdk/models/companies_company_id_users_post200_response_data'
require 'spartera_api_sdk/models/companies_company_id_users_user_id_alerts_alert_id_delete200_response'
require 'spartera_api_sdk/models/companies_company_id_users_user_id_alerts_alert_id_delete200_response_data'
require 'spartera_api_sdk/models/companies_company_id_users_user_id_alerts_alert_id_get200_response'
require 'spartera_api_sdk/models/companies_company_id_users_user_id_alerts_alert_id_patch200_response'
require 'spartera_api_sdk/models/companies_company_id_users_user_id_alerts_alert_id_patch200_response_data'
require 'spartera_api_sdk/models/companies_company_id_users_user_id_alerts_get200_response'
require 'spartera_api_sdk/models/companies_company_id_users_user_id_alerts_post200_response'
require 'spartera_api_sdk/models/companies_company_id_users_user_id_alerts_post200_response_data'
require 'spartera_api_sdk/models/companies_company_id_users_user_id_delete200_response'
require 'spartera_api_sdk/models/companies_company_id_users_user_id_delete200_response_data'
require 'spartera_api_sdk/models/companies_company_id_users_user_id_favorites_favorite_id_delete200_response'
require 'spartera_api_sdk/models/companies_company_id_users_user_id_favorites_favorite_id_delete200_response_data'
require 'spartera_api_sdk/models/companies_company_id_users_user_id_favorites_favorite_id_get200_response'
require 'spartera_api_sdk/models/companies_company_id_users_user_id_favorites_favorite_id_patch200_response'
require 'spartera_api_sdk/models/companies_company_id_users_user_id_favorites_favorite_id_patch200_response_data'
require 'spartera_api_sdk/models/companies_company_id_users_user_id_favorites_get200_response'
require 'spartera_api_sdk/models/companies_company_id_users_user_id_favorites_post200_response'
require 'spartera_api_sdk/models/companies_company_id_users_user_id_favorites_post200_response_data'
require 'spartera_api_sdk/models/companies_company_id_users_user_id_get200_response'
require 'spartera_api_sdk/models/companies_company_id_users_user_id_patch200_response'
require 'spartera_api_sdk/models/companies_company_id_users_user_id_patch200_response_data'
require 'spartera_api_sdk/models/company'
require 'spartera_api_sdk/models/connection'
require 'spartera_api_sdk/models/error'
require 'spartera_api_sdk/models/favorite'
require 'spartera_api_sdk/models/inline_object'
require 'spartera_api_sdk/models/inline_object1'
require 'spartera_api_sdk/models/inline_object2'
require 'spartera_api_sdk/models/inline_object3'
require 'spartera_api_sdk/models/me_get200_response'
require 'spartera_api_sdk/models/me_get200_response_api_key_info'
require 'spartera_api_sdk/models/me_get200_response_profile'
require 'spartera_api_sdk/models/me_get200_response_token_metadata'
require 'spartera_api_sdk/models/user'

# APIs
require 'spartera_api_sdk/api/api_keys_api'
require 'spartera_api_sdk/api/alerts_api'
require 'spartera_api_sdk/api/asset_price_history_api'
require 'spartera_api_sdk/api/assets_api'
require 'spartera_api_sdk/api/cloud_providers_api'
require 'spartera_api_sdk/api/companies_api'
require 'spartera_api_sdk/api/connections_api'
require 'spartera_api_sdk/api/favorites_api'
require 'spartera_api_sdk/api/storage_engines_api'
require 'spartera_api_sdk/api/users_api'

module SparteraApiSdk
  class << self
    # Customize default settings for the SDK using block.
    #   SparteraApiSdk.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
